#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Utilisation: $0 <topic>"
    echo "Exemple: $0 mytopic"
    echo "Cela exécutera la commande mosquitto_sub avec les paramètres par défaut."
    exit 1
fi

topic=$1

#mosquitto_sub -h $ip -p 8883 -t "$topic" --cafile /etc/mosquitto/certs/certificate.pem --cert /etc/mosquitto/certs/certificate.pem --key /etc/mosquitto/certs/key.pem --insecure
mosquitto_sub -h 192.168.1.148 -p 1883 -t "$topic"
