#!/bin/bash

configure_mosquitto() {
    printf "\nDébut de l'installation\n"
    apt update && apt upgrade -y
    apt install mosquitto mosquitto-clients openssl -y
    service mosquitto stop
    mkdir -p /etc/mosquitto/certs

    country = "FR"
    state = "BFC"
    city = "Montbeliard"
    organization = "IUT"
    common_name_serv = ""
    common_name = "192.168.1.50"

    openssl genrsa -des3 -out ca.key 2048
    openssl req -new -x509 -days 1826 -key ca.key -out ca.crt\
        -subj "/C=$country/ST=$state/L=$city/O=$organization/CN=$common_name_serv"

    openssl genrsa -out server.key 2048
    openssl req -new -out server.csr -key server.key \
        -subj "/C=$country/ST=$state/L=$city/O=$organization/CN=$common_name"

    openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 360

    cp server.* /etc/mosquitto/certs/
    cp ca.* /etc/mosquitto/certs/
    chmod 644 /etc/mosquitto/certs/*

    # Chemin du fichier de mots de passe
    password_file="/etc/mosquitto/auth.txt"

    # Vérifier si le fichier de mots de passe existe déjà
    if [ -f "$password_file" ]; then
        echo "Le fichier de mots de passe existe déjà."
    else
        echo "Le fichier de mots de passe n'existe pas. Création du fichier..."
        mosquitto_passwd -c "$password_file" "$default_username"
        chmod 600 "$password_file"
    fi

    # Ajouter l'utilisateur par défaut
    default_username="GRP-1-IOM"
    default_password="Porygon-Z#1"

    # Vérifier si l'utilisateur par défaut existe déjà dans le fichier de mots de passe
    if grep -q "^$default_username:" "$password_file"; then
        echo "L'utilisateur par défaut existe déjà dans le fichier de mots de passe."
    else
        echo "Ajout de l'utilisateur par défaut dans le fichier de mots de passe..."
        echo "$default_username:$(mosquitto_passwd -p <<< "$default_password")" >> "$password_file"
        echo "Utilisateur par défaut ajouté avec succès."
    fi

    #scp grp-1-iom@192.168.1.50:/etc/mosquitto/certs/ca.crt pi@192.168.1.60:/home/pi/Documents/ca.crt
    #scp grp-1-iom@192.168.1.50:/etc/mosquitto/certs/ca.crt /home/teto/Documents/Projet/Bash/ca.crt

    printf "\nConfiguration de Mosquitto\n"
    # Configuration de Mosquitto
    echo "listener 8883
allow_anonymous false
password_file /etc/mosquitto/auth.txt
cafile /etc/mosquitto/certs/ca.crt
keyfile /etc/mosquitto/certs/server.key
certfile /etc/mosquitto/certs/server.crt" > /etc/mosquitto/conf.d/default.conf
    printf "\nInstallation Terminé.\n"

}

# Appel de la fonction
configure_mosquitto
