#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Utilisation: $0 <IP> <topic>"
    echo "Exemple: $0 192.168.1.145 mytopic"
    echo "Cela exécutera la commande mosquitto_sub avec les paramètres par défaut."
    exit 1
fi

ip=$1
topic=$2

mosquitto_sub -h $ip -p 8883 -t "$topic" --cafile /etc/mosquitto/certs/certificate.pem --cert /etc/mosquitto/certs/certificate.pem --key /etc/mosquitto/certs/key.pem --insecure
